export const USER_TOKEN = "USER_TOKEN"
export const API_URL = "http://localhost:8080"
export const userConstants = {
 LOGIN_SUCCESS: 'LOGIN_SUCCESS',
 LOGIN_REQUEST: 'LOGIN_REQUEST',
 LOGIN_FAILURE: 'LOGIN_FAILURE',
 SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
 SIGNUP_REQUEST: 'SIGNUP_REQUEST',
 SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}
export const employeeConstants = {
 REQUEST: 'EMPLOYEE_REQUEST',
 SUCCESS: 'EMPLOYEE_SUCCESS',
 FAILURE: 'EMPLOYEE_FAILURE'
}
export const alertConstants = {
SUCCESS: 'ALERT_SUCCESS',
ERROR: 'ALERT_ERROR',
CLEAR: 'ALERT_CLEAR'
}